version: '3.7'
services:
    emailengine:
        restart: always
        image: andris9/emailengine
        ports:
            - '3000:3000'
        depends_on:
            - redis
        environment:
            CMD_ARGS: --dbs.redis=redis://redis:6379/2
    redis:
        image: redis:alpine
        restart: always
        volumes:
            - /data
