name: Notify discord
on:
    push:
        branches:
            - 'master'
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: send custom message with args
              uses: appleboy/discord-action@master
              with:
                  webhook_id: ${{ secrets.WEBHOOK_ID }}
                  webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
                  args: '**${{ github.actor }}** pushed [${{ github.sha }}](https://github.com/postalsys/emailengine/commit/${{ github.sha }}) to *${{ github.ref }}*'
